### PR TITLE
contrib: adding 'debounce'

### PR DESCRIPTION
**Pull request by karol-bujacek**
Debounce is very similar to 'after', the only difference is that events triggered within time interval resets timer.

### CODE REVIEW

**Comment by getify** [comment]
Thanks for the contribution. Can you explain how you use this? Is this only for reactive sequences, because I don't see how a normal sequence would benefit from it?

**Comment by karol-bujacek** [comment]
Yes, I’m using this only for reactive sequences. After your question I think that `plugin.reactHelpers.js` may be a better place for this.

I use this for example when I want to react to input field value changed. If `fromEvent` is responsible for JS event binding, I can use it like `var sequence = ASQ.react.fromEvent('#inputElement', 'change').debounce(1000).then([…])`which in human language should mean something like ‘wait a little bit if user will write any other character’.

**Comment by getify** [comment]
Yep, I like that functionality.

But TBH, the plugin mechanism that currently exists is more intended to add instance methods to main sequences. If you look at [plugin.react.js](https://github.com/getify/asynquence/blob/master/contrib/plugin.react.js#L24-L46), you'll notice that it has hard-coded additions to the reactive sequence instances, which is how this ought to be offered.

What I really need is to provide a mechanism like `ASQ.react.extend(..)` that can extend only reactive sequences. That's really the most appropriate way for this to be included.

But I do concur that it would be best bundled into `plugin.reactHelpers.js`.

If you'd like to take a pass at adding a `ASQ.react.extend(..)`, I'd be grateful for that contribution too. If not, I'll try to get to that soon. Ideally, it'd look/behave exactly like you've used `ASQ.extend(..)` already, so that would mean the only change to your plugin contribution would be to move it to the other file.

**Comment by getify** [comment]
So, I added `ASQ.react.extend(..)`, so if you could rework your PR to use that (and test it), that'd be super helpful. :)

**Comment by karol-bujacek** [comment]
Hello Kyle, sorry for slowness.
I’ve commited new version of ASQ.react.debounce. I’m not 100% sure if these changes are what did you write about, but it seems it is the best I can do at the moment.

I‘ve also created simple tests in contrib/tests.js.

**Pull request closed without merging**
